# Generated by Django 6.0.4 on 2026-04-10 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('pagina_lusofona', models.URLField(blank=True, verbose_name='Página na Lusófona')),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
            options={
                'verbose_name_plural': 'Docentes',
            },
        ),
        migrations.CreateModel(
            name='Licenciatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('instituicao', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('ano_inicio', models.IntegerField()),
                ('ano_fim', models.IntegerField(blank=True, null=True)),
                ('website', models.URLField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='licenciatura/')),
            ],
            options={
                'verbose_name_plural': 'Licenciaturas',
            },
        ),
        migrations.CreateModel(
            name='MakingOf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('entidade_relacionada', models.CharField(choices=[('licenciatura', 'Licenciatura'), ('unidade_curricular', 'Unidade Curricular'), ('projeto', 'Projeto'), ('tecnologia', 'Tecnologia'), ('tfc', 'TFC'), ('competencia', 'Competência'), ('formacao', 'Formação'), ('outro', 'Outro')], default='outro', max_length=50, verbose_name='Entidade relacionada')),
                ('descricao', models.TextField(verbose_name='Descrição / Decisões tomadas')),
                ('fotografia', models.ImageField(blank=True, null=True, upload_to='makingof/', verbose_name='Fotografia (caderno / DER / esquema)')),
                ('erros_correcoes', models.TextField(blank=True, verbose_name='Erros encontrados e correções')),
                ('uso_ia', models.TextField(blank=True, verbose_name='Uso de ferramentas de IA (se aplicável)')),
                ('data', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Making Of',
                'verbose_name_plural': 'Making Of',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='Tecnologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('linguagem', 'Linguagem de Programação'), ('framework', 'Framework'), ('base_dados', 'Base de Dados'), ('ferramenta', 'Ferramenta'), ('devops', 'DevOps / Infraestrutura'), ('outro', 'Outro')], default='outro', max_length=50)),
                ('descricao', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='tecnologias/')),
                ('website_oficial', models.URLField(blank=True)),
                ('nivel_interesse', models.IntegerField(choices=[(1, 'Iniciante'), (2, 'Básico'), (3, 'Intermédio'), (4, 'Avançado'), (5, 'Especialista')], default=3, verbose_name='Nível de interesse / proficiência')),
                ('destaque', models.BooleanField(default=False, verbose_name='Tecnologia em destaque')),
            ],
            options={
                'verbose_name_plural': 'Tecnologias',
                'ordering': ['-destaque', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='projetos/')),
                ('video_demo', models.URLField(blank=True, verbose_name='Vídeo demo')),
                ('repositorio_github', models.URLField(blank=True, verbose_name='Repositório GitHub')),
                ('conceitos_aplicados', models.TextField(blank=True, verbose_name='Conceitos aplicados da UC')),
                ('data_conclusao', models.DateField(blank=True, null=True, verbose_name='Data de conclusão')),
                ('destaque', models.BooleanField(default=False)),
                ('tecnologias', models.ManyToManyField(blank=True, related_name='projetos', to='portfolio.tecnologia')),
            ],
            options={
                'verbose_name_plural': 'Projetos',
                'ordering': ['-destaque', '-data_conclusao'],
            },
        ),
        migrations.CreateModel(
            name='Formacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('tipo', models.CharField(choices=[('academica', 'Académica'), ('curso', 'Curso / Formação'), ('certificacao', 'Certificação'), ('workshop', 'Workshop'), ('outro', 'Outro')], default='curso', max_length=30)),
                ('instituicao', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('data_inicio', models.DateField(verbose_name='Data de início')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Data de conclusão')),
                ('certificado', models.FileField(blank=True, null=True, upload_to='formacoes/certificados/')),
                ('link', models.URLField(blank=True)),
                ('tecnologias', models.ManyToManyField(blank=True, related_name='formacoes', to='portfolio.tecnologia')),
            ],
            options={
                'verbose_name': 'Formação',
                'verbose_name_plural': 'Formações',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Competencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('tecnica', 'Técnica'), ('soft', 'Soft skill'), ('linguistica', 'Linguística'), ('outra', 'Outra')], default='tecnica', max_length=30)),
                ('descricao', models.TextField(blank=True)),
                ('nivel', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3, verbose_name='Nível (1-5)')),
                ('projetos', models.ManyToManyField(blank=True, related_name='competencias', to='portfolio.projeto')),
                ('tecnologias', models.ManyToManyField(blank=True, related_name='competencias', to='portfolio.tecnologia')),
            ],
            options={
                'verbose_name_plural': 'Competências',
                'ordering': ['tipo', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='TFC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('tipo', models.CharField(choices=[('licenciatura', 'Trabalho Final de Licenciatura'), ('mestrado', 'Dissertação de Mestrado'), ('outro', 'Outro')], default='licenciatura', max_length=30)),
                ('autor', models.CharField(max_length=200)),
                ('orientador', models.CharField(blank=True, max_length=200)),
                ('ano', models.IntegerField()),
                ('resumo', models.TextField(blank=True)),
                ('palavras_chave', models.CharField(blank=True, max_length=300, verbose_name='Palavras-chave')),
                ('link', models.URLField(blank=True, verbose_name='Link para o TFC')),
                ('destaque', models.BooleanField(default=False, verbose_name='TFC em destaque')),
                ('tecnologias', models.ManyToManyField(blank=True, related_name='tfcs', to='portfolio.tecnologia')),
            ],
            options={
                'verbose_name': 'TFC',
                'verbose_name_plural': 'TFCs',
                'ordering': ['-destaque', '-ano'],
            },
        ),
        migrations.CreateModel(
            name='UnidadeCurricular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('sigla', models.CharField(blank=True, max_length=20)),
                ('ano', models.IntegerField(verbose_name='Ano curricular')),
                ('semestre', models.IntegerField(choices=[(1, '1º Semestre'), (2, '2º Semestre')])),
                ('ects', models.IntegerField(verbose_name='Créditos ECTS')),
                ('descricao', models.TextField(blank=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='unidades_curriculares/')),
                ('docentes', models.ManyToManyField(blank=True, related_name='unidades_curriculares', to='portfolio.docente')),
                ('licenciatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades_curriculares', to='portfolio.licenciatura')),
            ],
            options={
                'verbose_name': 'Unidade Curricular',
                'verbose_name_plural': 'Unidades Curriculares',
                'ordering': ['ano', 'semestre', 'nome'],
            },
        ),
        migrations.AddField(
            model_name='projeto',
            name='uc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projetos', to='portfolio.unidadecurricular', verbose_name='Unidade Curricular'),
        ),
    ]
