# Generated by Django 6.0.4 on 2026-04-10 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidadecurricular',
            name='semestre',
            field=models.IntegerField(choices=[(0, 'Anual'), (1, '1º Semestre'), (2, '2º Semestre')]),
        ),
    ]
