# Generated by Django 6.0.4 on 2026-05-13 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_unidadecurricular_semestre'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoTecnologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Tipo de Tecnologia',
                'verbose_name_plural': 'Tipos de Tecnologia',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='tecnologia',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tecnologias', to='portfolio.tipotecnologia'),
        ),
    ]
